package planetario;
// Generated 09/05/2016 20:00:11 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Estrelas generated by hbm2java
 */
public class Estrelas  implements java.io.Serializable {


     private String nome;
     private float ra;
     private float dec2;
     private Float distancia;
     private Float metalicidade;
     private Float massa;
     private Float raio;
     private Float idade;
     private Float temperatura;
     private Set planetas = new HashSet(0);

    public Estrelas() {
    }

	
    public Estrelas(String nome, float ra, float dec2) {
        this.nome = nome;
        this.ra = ra;
        this.dec2 = dec2;
    }
    public Estrelas(String nome, float ra, float dec2, Float distancia, Float metalicidade, Float massa, Float raio, Float idade, Float temperatura, Set planetas) {
       this.nome = nome;
       this.ra = ra;
       this.dec2 = dec2;
       this.distancia = distancia;
       this.metalicidade = metalicidade;
       this.massa = massa;
       this.raio = raio;
       this.idade = idade;
       this.temperatura = temperatura;
       this.planetas = planetas;
    }
   
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public float getRa() {
        return this.ra;
    }
    
    public void setRa(float ra) {
        this.ra = ra;
    }
    public float getDec2() {
        return this.dec2;
    }
    
    public void setDec2(float dec2) {
        this.dec2 = dec2;
    }
    public Float getDistancia() {
        return this.distancia;
    }
    
    public void setDistancia(Float distancia) {
        this.distancia = distancia;
    }
    public Float getMetalicidade() {
        return this.metalicidade;
    }
    
    public void setMetalicidade(Float metalicidade) {
        this.metalicidade = metalicidade;
    }
    public Float getMassa() {
        return this.massa;
    }
    
    public void setMassa(Float massa) {
        this.massa = massa;
    }
    public Float getRaio() {
        return this.raio;
    }
    
    public void setRaio(Float raio) {
        this.raio = raio;
    }
    public Float getIdade() {
        return this.idade;
    }
    
    public void setIdade(Float idade) {
        this.idade = idade;
    }
    public Float getTemperatura() {
        return this.temperatura;
    }
    
    public void setTemperatura(Float temperatura) {
        this.temperatura = temperatura;
    }
    public Set getPlanetas() {
        return this.planetas;
    }
    
    public void setPlanetas(Set planetas) {
        this.planetas = planetas;
    }




}


