package planetario;
// Generated 09/05/2016 20:00:11 by Hibernate Tools 4.3.1



/**
 * PlanetaId generated by hbm2java
 */
public class PlanetaId  implements java.io.Serializable {


     private int idPlaneta;
     private String estrelasNome;

    public PlanetaId() {
    }

    public PlanetaId(int idPlaneta, String estrelasNome) {
       this.idPlaneta = idPlaneta;
       this.estrelasNome = estrelasNome;
    }
   
    public int getIdPlaneta() {
        return this.idPlaneta;
    }
    
    public void setIdPlaneta(int idPlaneta) {
        this.idPlaneta = idPlaneta;
    }
    public String getEstrelasNome() {
        return this.estrelasNome;
    }
    
    public void setEstrelasNome(String estrelasNome) {
        this.estrelasNome = estrelasNome;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PlanetaId) ) return false;
		 PlanetaId castOther = ( PlanetaId ) other; 
         
		 return (this.getIdPlaneta()==castOther.getIdPlaneta())
 && ( (this.getEstrelasNome()==castOther.getEstrelasNome()) || ( this.getEstrelasNome()!=null && castOther.getEstrelasNome()!=null && this.getEstrelasNome().equals(castOther.getEstrelasNome()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdPlaneta();
         result = 37 * result + ( getEstrelasNome() == null ? 0 : this.getEstrelasNome().hashCode() );
         return result;
   }   


}


