package planetario;
// Generated Jun 4, 2016 5:16:00 PM by Hibernate Tools 4.3.1



/**
 * PlanetaId generated by hbm2java
 */
public class PlanetaId  implements java.io.Serializable {


     private int idPlaneta;
     private String estrelasNome;

    public PlanetaId() {
    }

    public PlanetaId(int idPlaneta, String estrelasNome) {
       this.idPlaneta = idPlaneta;
       this.estrelasNome = estrelasNome;
    }
   
    public int getIdPlaneta() {
        return this.idPlaneta;
    }
    
    public void setIdPlaneta(int idPlaneta) {
        this.idPlaneta = idPlaneta;
    }
    public String getEstrelasNome() {
        return this.estrelasNome;
    }
    
    public void setEstrelasNome(String estrelasNome) {
        this.estrelasNome = estrelasNome;
    }




}


